### PR TITLE
feat: update unused voucher copy

### PR DESCRIPTION
**Pull request by jacoblb64**
updating with latest copy from the doc, but still some open questions:

- one email per voucher, per merchant, or per person?
- copy to reflect the above
- including an expiration date in the email, or in the table
- updating expiration date for gift cards in the DB?
- sending email -- `receipts`, or something else? `hello`?

### CODE REVIEW

**Comment by jacoblb64** [comment]
Current email looks like this: (name missing)
Screen Shot 2021-07-15 at 8 18 59 PM

**Review by stanzheng — APPROVED** [review]
not sure if subject line is in stone but this is good!

**Comment by stanzheng** [comment]
@jacoblb64 @kaiserfenix taking lings feedback the word Sunsetting should be changed to `Retiring" or  'discontinuing`

**Comment by stanzheng** [comment]
https://docs.google.com/document/d/1yHWRmNkBLe6PsbHb9ZNrra51FjiKc6lZ_miiYLNaonw/edit?disco=AAAANdT15eU

**Comment by jacoblb64** [comment]
Current copy as of latest commit

(purple color is gmail quoting as I've been sending lots for testing)
(missing spaces have been fixed since)

Screen Shot 2021-07-18 at 5 33 07 PM

**Comment by jacoblb64** [comment]
Copy as of 7/28

image

**Pull request merged**
