### PR TITLE
Wilson/add total contributions route

### PR DESCRIPTION
**Pull request by wilsonj806**
# [Ticket](https://trello.com/c/eu6uDsZQ)
Backend portion of the above Trello ticket. Adds a new endpoint: `GET /sellers/total_contributions`

## Code added:
- `SellersHelpers.collect_contribution_amounts`
- `seller#get_contributions`

## Response format:
```json
{
  "donation_amount": 9999,
  "gift_card_amount": 99999,
  "gift_a_meal_amount": 99999
}
```

### CODE REVIEW

**Comment by wilsonj806** [comment]
[[HIGH PRIORITY] Improve merchant directory load times](https://trello.com/c/eu6uDsZQ/831-high-priority-improve-merchant-directory-load-times)

**Review by stanzheng — APPROVED** [review]
LGTM, adding new endpoints seems fine, unsure greater scheme how this will speed up but interested!

**Comment by wilsonj806** [comment]
My train of thought was that splitting it means we can have part of the page rendered while all the sellers load rather than the entire screen be blank. But yeah it probably realistically doesn't do much

**Comment by stanzheng** [comment]
Sounds good to me !

**Pull request merged**
