### PR TITLE
Cleanup unused stripe code in controller and specs

### PR DESCRIPTION
**Pull request by Yong-L**
Cleaning up unused stripe code

### CODE REVIEW

**Comment by jtmckibb** [comment]
You can delete the keys in the .env file as well. Also if you could delete the migrations via a migration, that would also be awesome

**Comment by Yong-L** [comment]
so just drop the columns?

**Comment by jtmckibb** [comment]
Yeah you can just drop the columns bc we have no Stripe PaymentIntents in prod

**Comment by jtmckibb** [comment]
Actually maybe we should keep them just in case —

**Comment by Yong-L** [comment]
In case of like backwards compat issues?

**Pull request merged**
